/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  // react-markdown v9 and the entire unified/micromark ecosystem are ESM-only.
  // Without this list webpack cannot bundle them for client-side rendering,
  // causing a silent hydration crash (blank white page).
  transpilePackages: [
    "react-markdown",
    "remark-gfm",
    "remark-parse",
    "remark-rehype",
    "unified",
    "bail",
    "is-plain-obj",
    "trough",
    "vfile",
    "vfile-message",
    "unist-util-stringify-position",
    "mdast-util-from-markdown",
    "mdast-util-to-markdown",
    "mdast-util-to-hast",
    "mdast-util-gfm",
    "mdast-util-gfm-autolink-literal",
    "mdast-util-gfm-footnote",
    "mdast-util-gfm-strikethrough",
    "mdast-util-gfm-table",
    "mdast-util-gfm-task-list-item",
    "micromark",
    "micromark-extension-gfm",
    "micromark-extension-gfm-autolink-literal",
    "micromark-extension-gfm-footnote",
    "micromark-extension-gfm-strikethrough",
    "micromark-extension-gfm-table",
    "micromark-extension-gfm-tagfilter",
    "micromark-extension-gfm-task-list-item",
    "micromark-util-character",
    "micromark-util-chunked",
    "micromark-util-combine-extensions",
    "micromark-util-decode-numeric-character-reference",
    "micromark-util-decode-string",
    "micromark-util-encode",
    "micromark-util-html-tag-name",
    "micromark-util-normalize-identifier",
    "micromark-util-resolve-all",
    "micromark-util-sanitize-uri",
    "micromark-util-subtokenize",
    "micromark-util-symbol",
    "micromark-util-types",
    "decode-named-character-reference",
    "character-entities",
    "property-information",
    "hast-util-whitespace",
    "hast-util-to-jsx-runtime",
    "hast-util-is-element",
    "space-separated-tokens",
    "comma-separated-tokens",
    "unist-util-position",
    "unist-util-visit",
    "unist-util-visit-parents",
    "unist-util-remove-position",
    "unist-util-generated",
    "estree-util-is-identifier-name",
    "devlop",
    "html-url-attributes",
  ],
};

module.exports = nextConfig;
